-- Seed data for DME and DVOR equipment templates
-- Insert default templates for JSON-based equipment

INSERT INTO equipment_templates (name, equipment_type, brand, model, parser_config, default_thresholds, description, is_system) VALUES
('DME Standard Template', 'dme', 'Generic', 'DME-100', '{
  "mappings": [
    {"name": "txp1_active", "json_path": "TXP1.active", "type": "boolean"},
    {"name": "txp1_ident", "json_path": "TXP1.ident", "type": "string"},
    {"name": "txp1_mon1_sys_delay", "json_path": "TXP1.mon1.sys_delay", "type": "number", "unit": "ms"},
    {"name": "txp1_mon1_rise_a", "json_path": "TXP1.mon1.rise_a", "type": "number", "unit": "µs"},
    {"name": "txp1_mon1_decay_a", "json_path": "TXP1.mon1.decay_a", "type": "number", "unit": "µs"},
    {"name": "txp1_mon1_dur_a", "json_path": "TXP1.mon1.dur_a", "type": "number", "unit": "µs"},
    {"name": "txp1_mon1_spacing", "json_path": "TXP1.mon1.spacing", "type": "number", "unit": "µs"},
    {"name": "txp1_mon1_reply_eff", "json_path": "TXP1.mon1.reply_eff", "type": "number", "unit": "%"},
    {"name": "txp1_mon1_pair_rate", "json_path": "TXP1.mon1.pair_rate", "type": "number", "unit": "Hz"},
    {"name": "txp1_mon1_fwd_power", "json_path": "TXP1.mon1.fwd_power", "type": "number", "unit": "W"},
    {"name": "txp1_mon2_sys_delay", "json_path": "TXP1.mon2.sys_delay", "type": "number", "unit": "ms"},
    {"name": "txp1_mon2_rise_a", "json_path": "TXP1.mon2.rise_a", "type": "number", "unit": "µs"},
    {"name": "txp1_mon2_decay_a", "json_path": "TXP1.mon2.decay_a", "type": "number", "unit": "µs"},
    {"name": "txp1_mon2_dur_a", "json_path": "TXP1.mon2.dur_a", "type": "number", "unit": "µs"},
    {"name": "txp1_mon2_spacing", "json_path": "TXP1.mon2.spacing", "type": "number", "unit": "µs"},
    {"name": "txp1_mon2_reply_eff", "json_path": "TXP1.mon2.reply_eff", "type": "number", "unit": "%"},
    {"name": "txp1_mon2_pair_rate", "json_path": "TXP1.mon2.pair_rate", "type": "number", "unit": "Hz"},
    {"name": "txp1_mon2_fwd_power", "json_path": "TXP1.mon2.fwd_power", "type": "number", "unit": "W"},
    {"name": "txp2_active", "json_path": "TXP2.active", "type": "boolean"},
    {"name": "txp2_ident", "json_path": "TXP2.ident", "type": "string"},
    {"name": "txp2_mon1_sys_delay", "json_path": "TXP2.mon1.sys_delay", "type": "number", "unit": "ms"},
    {"name": "txp2_mon1_rise_a", "json_path": "TXP2.mon1.rise_a", "type": "number", "unit": "µs"},
    {"name": "txp2_mon1_decay_a", "json_path": "TXP2.mon1.decay_a", "type": "number", "unit": "µs"},
    {"name": "txp2_mon1_dur_a", "json_path": "TXP2.mon1.dur_a", "type": "number", "unit": "µs"},
    {"name": "txp2_mon1_spacing", "json_path": "TXP2.mon1.spacing", "type": "number", "unit": "µs"},
    {"name": "txp2_mon1_reply_eff", "json_path": "TXP2.mon1.reply_eff", "type": "number", "unit": "%"},
    {"name": "txp2_mon1_pair_rate", "json_path": "TXP2.mon1.pair_rate", "type": "number", "unit": "Hz"},
    {"name": "txp2_mon1_fwd_power", "json_path": "TXP2.mon1.fwd_power", "type": "number", "unit": "W"},
    {"name": "txp2_mon2_sys_delay", "json_path": "TXP2.mon2.sys_delay", "type": "number", "unit": "ms"},
    {"name": "txp2_mon2_rise_a", "json_path": "TXP2.mon2.rise_a", "type": "number", "unit": "µs"},
    {"name": "txp2_mon2_decay_a", "json_path": "TXP2.mon2.decay_a", "type": "number", "unit": "µs"},
    {"name": "txp2_mon2_dur_a", "json_path": "TXP2.mon2.dur_a", "type": "number", "unit": "µs"},
    {"name": "txp2_mon2_spacing", "json_path": "TXP2.mon2.spacing", "type": "number", "unit": "µs"},
    {"name": "txp2_mon2_reply_eff", "json_path": "TXP2.mon2.reply_eff", "type": "number", "unit": "%"},
    {"name": "txp2_mon2_pair_rate", "json_path": "TXP2.mon2.pair_rate", "type": "number", "unit": "Hz"},
    {"name": "txp2_mon2_fwd_power", "json_path": "TXP2.mon2.fwd_power", "type": "number", "unit": "W"},
    {"name": "system_packets", "json_path": "system.packets", "type": "number"},
    {"name": "system_connected", "json_path": "system.connected", "type": "boolean"}
  ],
  "alarm_rules": [
    {"parameter": "txp1_mon1_reply_eff", "operator": "lt", "value": 90, "severity": "warning", "message": "TXP1 MON1 Reply Efficiency < 90%"},
    {"parameter": "txp1_mon2_reply_eff", "operator": "lt", "value": 90, "severity": "warning", "message": "TXP1 MON2 Reply Efficiency < 90%"},
    {"parameter": "txp2_mon1_reply_eff", "operator": "lt", "value": 90, "severity": "warning", "message": "TXP2 MON1 Reply Efficiency < 90%"},
    {"parameter": "txp2_mon2_reply_eff", "operator": "lt", "value": 90, "severity": "warning", "message": "TXP2 MON2 Reply Efficiency < 90%"},
    {"parameter": "txp1_mon1_fwd_power", "operator": "lt", "value": 800, "severity": "alarm", "message": "TXP1 MON1 Forward Power < 800W"},
    {"parameter": "txp2_mon2_fwd_power", "operator": "lt", "value": 800, "severity": "alarm", "message": "TXP2 MON2 Forward Power < 800W"},
    {"parameter": "system_connected", "operator": "eq", "value": false, "severity": "alarm", "message": "System not connected"}
  ]
}', '{}', 'Standard DME equipment template with comprehensive monitoring parameters', TRUE),

('DVOR Standard Template', 'dvor', 'Generic', 'DVOR-200', '{
  "mappings": [
    {"name": "mon1_carrier_power", "json_path": "MON1.carrier_power", "type": "number", "unit": "dBm"},
    {"name": "mon1_rf_input", "json_path": "MON1.rf_input", "type": "number", "unit": "dBm"},
    {"name": "mon1_azimuth", "json_path": "MON1.azimuth", "type": "number", "unit": "deg"},
    {"name": "mon1_carrier_freq", "json_path": "MON1.carrier_freq", "type": "number", "unit": "MHz"},
    {"name": "mon1_usb_freq", "json_path": "MON1.usb_freq", "type": "number", "unit": "MHz"},
    {"name": "mon1_lsb_freq", "json_path": "MON1.lsb_freq", "type": "number", "unit": "MHz"},
    {"name": "mon1_am_30hz", "json_path": "MON1.am_30hz", "type": "number", "unit": "%"},
    {"name": "mon1_am_9960hz", "json_path": "MON1.am_9960hz", "type": "number", "unit": "%"},
    {"name": "mon1_am_1020hz", "json_path": "MON1.am_1020hz", "type": "number", "unit": "%"},
    {"name": "mon1_fm_index", "json_path": "MON1.fm_index", "type": "number"},
    {"name": "mon1_ident", "json_path": "MON1.ident", "type": "string"},
    {"name": "mon1_tsg_30hz", "json_path": "MON1.tsg_30hz", "type": "number", "unit": "Hz"},
    {"name": "mon1_tsg_azimuth", "json_path": "MON1.tsg_azimuth", "type": "number", "unit": "deg"},
    {"name": "mon2_carrier_power", "json_path": "MON2.carrier_power", "type": "number", "unit": "dBm"},
    {"name": "mon2_rf_input", "json_path": "MON2.rf_input", "type": "number", "unit": "dBm"},
    {"name": "mon2_azimuth", "json_path": "MON2.azimuth", "type": "number", "unit": "deg"},
    {"name": "mon2_carrier_freq", "json_path": "MON2.carrier_freq", "type": "number", "unit": "MHz"},
    {"name": "mon2_usb_freq", "json_path": "MON2.usb_freq", "type": "number", "unit": "MHz"},
    {"name": "mon2_lsb_freq", "json_path": "MON2.lsb_freq", "type": "number", "unit": "MHz"},
    {"name": "mon2_am_30hz", "json_path": "MON2.am_30hz", "type": "number", "unit": "%"},
    {"name": "mon2_am_9960hz", "json_path": "MON2.am_9960hz", "type": "number", "unit": "%"},
    {"name": "mon2_am_1020hz", "json_path": "MON2.am_1020hz", "type": "number", "unit": "%"},
    {"name": "mon2_fm_index", "json_path": "MON2.fm_index", "type": "number"},
    {"name": "mon2_ident", "json_path": "MON2.ident", "type": "string"},
    {"name": "tx1_carrier_power", "json_path": "TX1.carrier_power", "type": "number", "unit": "dBm"},
    {"name": "tx1_usb_sin", "json_path": "TX1.usb_sin", "type": "number"},
    {"name": "tx1_usb_cos", "json_path": "TX1.usb_cos", "type": "number"},
    {"name": "tx1_lsb_sin", "json_path": "TX1.lsb_sin", "type": "number"},
    {"name": "tx1_lsb_cos", "json_path": "TX1.lsb_cos", "type": "number"},
    {"name": "tx1_az_offset", "json_path": "TX1.az_offset", "type": "number", "unit": "deg"},
    {"name": "tx1_am_30hz", "json_path": "TX1.am_30hz", "type": "number", "unit": "%"},
    {"name": "tx1_am_1020hz", "json_path": "TX1.am_1020hz", "type": "number", "unit": "%"},
    {"name": "tx1_phase_offset", "json_path": "TX1.phase_offset", "type": "number", "unit": "deg"},
    {"name": "tx1_cpa_temp", "json_path": "TX1.cpa_temp", "type": "number", "unit": "°C"},
    {"name": "tx1_msg_temp", "json_path": "TX1.msg_temp", "type": "number", "unit": "°C"},
    {"name": "tx1_ident", "json_path": "TX1.ident", "type": "string"},
    {"name": "tx2_carrier_power", "json_path": "TX2.carrier_power", "type": "number", "unit": "dBm"},
    {"name": "tx2_usb_sin", "json_path": "TX2.usb_sin", "type": "number"},
    {"name": "tx2_usb_cos", "json_path": "TX2.usb_cos", "type": "number"},
    {"name": "tx2_lsb_sin", "json_path": "TX2.lsb_sin", "type": "number"},
    {"name": "tx2_lsb_cos", "json_path": "TX2.lsb_cos", "type": "number"},
    {"name": "tx2_az_offset", "json_path": "TX2.az_offset", "type": "number", "unit": "deg"},
    {"name": "tx2_am_30hz", "json_path": "TX2.am_30hz", "type": "number", "unit": "%"},
    {"name": "tx2_am_1020hz", "json_path": "TX2.am_1020hz", "type": "number", "unit": "%"},
    {"name": "tx2_phase_offset", "json_path": "TX2.phase_offset", "type": "number", "unit": "deg"},
    {"name": "tx2_cpa_temp", "json_path": "TX2.cpa_temp", "type": "number", "unit": "°C"},
    {"name": "tx2_msg_temp", "json_path": "TX2.msg_temp", "type": "number", "unit": "°C"},
    {"name": "tx2_ident", "json_path": "TX2.ident", "type": "string"},
    {"name": "lcu_dc_5v", "json_path": "LCU.dc_5v", "type": "number", "unit": "V"},
    {"name": "lcu_dc_7v", "json_path": "LCU.dc_7v", "type": "number", "unit": "V"},
    {"name": "lcu_dc_15v", "json_path": "LCU.dc_15v", "type": "number", "unit": "V"},
    {"name": "lcu_dc_28v", "json_path": "LCU.dc_28v", "type": "number", "unit": "V"},
    {"name": "lcu_ac_28v", "json_path": "LCU.ac_28v", "type": "number", "unit": "V"},
    {"name": "lcu_msg1_comm", "json_path": "LCU.msg1_comm", "type": "string"},
    {"name": "lcu_msg2_comm", "json_path": "LCU.msg2_comm", "type": "string"},
    {"name": "lcu_mon1_comm", "json_path": "LCU.mon1_comm", "type": "string"},
    {"name": "lcu_mon2_comm", "json_path": "LCU.mon2_comm", "type": "string"},
    {"name": "lcu_battery1", "json_path": "LCU.battery1", "type": "string"},
    {"name": "lcu_battery2", "json_path": "LCU.battery2", "type": "string"},
    {"name": "lcu_acdc1", "json_path": "LCU.acdc1", "type": "string"},
    {"name": "lcu_acdc2", "json_path": "LCU.acdc2", "type": "string"},
    {"name": "system_tx_active", "json_path": "system.tx_active", "type": "number"},
    {"name": "system_packets", "json_path": "system.packets", "type": "number"},
    {"name": "system_errors", "json_path": "system.errors", "type": "number"}
  ],
  "alarm_rules": [
    {"parameter": "mon1_carrier_power", "operator": "lt", "value": 80, "severity": "warning", "message": "MON1 Carrier Power < 80dBm"},
    {"parameter": "mon2_carrier_power", "operator": "lt", "value": 80, "severity": "warning", "message": "MON2 Carrier Power < 80dBm"},
    {"parameter": "tx1_carrier_power", "operator": "lt", "value": 80, "severity": "warning", "message": "TX1 Carrier Power < 80dBm"},
    {"parameter": "tx2_carrier_power", "operator": "lt", "value": 80, "severity": "warning", "message": "TX2 Carrier Power < 80dBm"},
    {"parameter": "mon1_azimuth", "operator": "gt", "value": 120, "severity": "alarm", "message": "MON1 Azimuth deviation > 120°"},
    {"parameter": "mon2_azimuth", "operator": "gt", "value": 120, "severity": "alarm", "message": "MON2 Azimuth deviation > 120°"},
    {"parameter": "lcu_dc_5v", "operator": "lt", "value": 4.5, "severity": "alarm", "message": "DC 5V supply < 4.5V"},
    {"parameter": "lcu_dc_28v", "operator": "lt", "value": 24, "severity": "alarm", "message": "DC 28V supply < 24V"},
    {"parameter": "system_errors", "operator": "gt", "value": 10, "severity": "warning", "message": "System errors > 10"}
  ]
}', '{}', 'Standard DVOR equipment template with comprehensive monitoring parameters', TRUE);